name: SDK Test

on:
 pull_request:

jobs:
 unit-test:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2

     - name: Print environment info
       run: |
         java -version
         ./gradlew --version
         echo "Free space:"
         df -h

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Run unit tests
       run: ./gradlew :xendit-android:connectedCheck --info

 # notify-slack:
 #   needs: unit-test
 #   runs-on: ubuntu-latest
 #   if: always()
 #   steps:
 #     - name: Notify Slack
 #       uses: ravsamhq/notify-slack-action@v1
 #       with:
 #         status: ${{ needs.unit-test.result }}
 #         footer: 'Linked Repo <{repo_url}|{repo}> {branch}'
 #         notify_when: 'failure'
 #       env:
 #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
