name: SDK Test

on:
 pull_request:

jobs:
 unit-test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3

     - name: Gradle cache
       uses: gradle/gradle-build-action@v2

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Touch local properties
       run: touch local.properties

#     - name: AVD cache
#       uses: actions/cache@v3
#       id: avd-cache
#       with:
#         path: |
#           ~/.android/avd/*
#           ~/.android/adb*
#         key: avd-29

#     - name: create AVD and generate snapshot for caching
#       if: steps.avd-cache.outputs.cache-hit != 'true'
#       uses: reactivecircus/android-emulator-runner@v2
#       with:
#         api-level: 29
#         arch: arm64-v8a
#         force-avd-creation: false
#         emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#         disable-animations: false
#         ram-size: 4096M
#         script: echo "Generated AVD snapshot for caching."

     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2

     - name: Print environment info
       run: |
         java -version
         ./gradlew --version
         echo "Free space:"
         df -h

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Run Instrumentation Test
       uses: reactivecircus/android-emulator-runner@v2
       with:
#         emulator-build: 7425822
         api-level: 30
         target: google_apis
         arch: x86_64
#         force-avd-creation: false
         ram-size: 4096M
         script: ./gradlew :xendit-android:connectedCheck --stacktrace

 # notify-slack:
 #   needs: unit-test
 #   runs-on: ubuntu-latest
 #   if: always()
 #   steps:
 #     - name: Notify Slack
 #       uses: ravsamhq/notify-slack-action@v1
 #       with:
 #         status: ${{ needs.unit-test.result }}
 #         footer: 'Linked Repo <{repo_url}|{repo}> {branch}'
 #         notify_when: 'failure'
 #       env:
 #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
